import { defineProblem } from '../types';

/** DRAFT wording, from the Interaction & Admin Visual Spec, F1. The claim is shown as someone's statement. */
export default defineProblem({
  id: 'F1',
  slug: 'house-flip',
  title: 'The $10K House Flip',
  version: 1,
  active: true,
  draft: true,
  module: 'feasibility',
  deca_category: 'decision_making',
  families: ['feasibility', 'percent'],
  scenario: {
    layout: 'claim',
    who: '@flipwithfred',
    source: 'speech',
    claim: 'Buy a house for $10,000, fix it up, and sell it for $20,000. Easy $10,000 profit!',
    facts: [
      { label: 'Buy price', value: '$10,000' },
      { label: 'Repairs', value: '$6,000' },
      { label: 'Buying costs', value: '$500' },
      { label: 'Holding costs (165 days)', value: '$1,000' },
      { label: 'Sale price', value: '$20,000' },
      { label: 'Selling costs', value: '8% of the sale price' },
    ],
  },
  // The gut rating is collected before any other cost-related problem (S4 sneakers fees, F5 resale fees).
  order: { before: ['S4', 'F5'], notAdjacent: ['S4', 'S5'] },
  steps: [
    {
      id: 'gut',
      kind: 'rating_gut',
      label: 'Gut rating',
      prompt: 'How believable is this claim? Go with your gut.',
      input: { type: 'dial' },
    },
    {
      id: 's1',
      kind: 'choice',
      label: 'Step 1 · where would the money come from',
      prompt: 'Where would you get $10,000 to buy the house?',
      input: {
        type: 'choice',
        options: [
          { id: 'savings', label: 'My savings' },
          { id: 'loan', label: 'A loan' },
          { id: 'parents', label: 'Parents or family' },
          { id: 'other', label: 'Somewhere else' },
        ],
      },
    },
    {
      id: 's2',
      kind: 'choice',
      label: 'Step 2 · why would the seller sell low',
      prompt: 'Why would a seller take half of what the finished house is worth? Pick all that could be true.',
      input: {
        type: 'choice',
        multi: true,
        options: [
          { id: 'needs_work', label: 'The house needs a lot of work' },
          { id: 'location', label: 'It is in a hard-to-sell place' },
          { id: 'hidden', label: 'It may have hidden problems' },
          { id: 'inattentive', label: 'The seller isn’t paying attention' },
          { id: 'other', label: 'Something else' },
        ],
      },
    },
    {
      id: 's2t',
      kind: 'why',
      label: 'Step 2 · your reason',
      prompt: 'Anything else you’d want to know about why the price is so low? Write a short answer, or skip.',
      input: { type: 'text', placeholder: 'Type a short answer. Please don’t type any names.' },
      optional: true,
    },
    {
      id: 's3',
      kind: 'control',
      label: 'Step 3 · selling costs',
      prompt: 'Selling costs are 8% of the sale price. How many dollars is that when the house sells for $20,000?',
      input: { type: 'number', unit: 'usd' },
      correct: 1600,
      codes: [
        { code: 'PAD', value: 8 },
        { code: 'DEC', value: 160 },
      ],
    },
    {
      id: 's4a',
      kind: 'guided',
      label: 'Step 4a · build the deal',
      prompt: 'Which of these are part of what you actually pay in this deal? Tap the ones that count.',
      input: {
        type: 'stack',
        poolLabel: 'Cards',
        areaLabel: 'What counts in this deal',
        cards: [
          { id: 'purchase', label: 'Buy price', amount: '$10,000' },
          { id: 'repairs', label: 'Repairs', amount: '$6,000' },
          { id: 'buying', label: 'Buying costs', amount: '$500' },
          { id: 'holding', label: 'Holding costs (165 days)', amount: '$1,000' },
          { id: 'selling', label: 'Selling costs', amount: '8% of the sale price' },
          { id: 'mailbox', label: 'A fancy new mailbox', amount: '$150', distractor: true },
          { id: 'charm', label: 'A lucky charm', amount: '$20', distractor: true },
        ],
      },
    },
    {
      id: 's4b',
      kind: 'guided',
      label: 'Step 4b · net profit',
      prompt: 'After everything you counted, how much money do you actually make? (The sale price is $20,000.)',
      input: { type: 'number', unit: 'usd' },
      correct: 900,
      codes: [
        { code: 'GROSS', value: 10000 },
        { code: 'MISS', value: 4000 },
        { code: 'MISS', value: 3500 },
        { code: 'MISS', value: 2500 },
        { code: 'MISS', value: 2400 },
      ],
    },
    {
      id: 's5a',
      kind: 'guided',
      label: 'Step 5a · total cash in',
      prompt: 'In total, how much money do you put into the deal? Count everything you pay, including the selling costs.',
      input: { type: 'number', unit: 'usd' },
      correct: 19100,
      codes: [
        { code: 'MISS', value: 17500 },
        { code: 'MISS', value: 16000 },
        { code: 'GROSS', value: 10000 },
      ],
    },
    {
      id: 's5b',
      kind: 'guided',
      label: 'Step 5b · return on that money',
      prompt: 'What percent do you earn on the money you put in? (Profit ÷ total cash in.)',
      input: { type: 'number', unit: 'percent' },
      calculator: true,
      correct: 4.71,
      codes: [
        { code: 'MISS', value: 5.14 },
        { code: 'GROSS', value: 100 },
      ],
    },
    {
      id: 's6',
      kind: 'guided',
      label: 'Step 6 · yearly rate',
      prompt: 'The whole deal takes 165 days. If you earned that same percent again and again, about what would it be in a full year (365 days)?',
      input: { type: 'number', unit: 'percent' },
      calculator: true,
      correct: 10.42,
      correctTolPct: 3.5,
      codes: [{ code: 'GROSS', value: 221.2 }],
    },
    {
      id: 's7',
      kind: 'guided',
      label: 'Step 7 · break-even sale price',
      prompt: 'Selling costs are 8% of whatever the sale price is. What is the lowest sale price where you still make $0 profit?',
      input: { type: 'number', unit: 'usd' },
      calculator: true,
      correct: 19021.74,
      codes: [{ code: 'MISS', value: 17500 }],
    },
    {
      id: 's8a',
      kind: 'choice',
      label: 'Step 8a · repairs cost more',
      prompt: 'The repairs end up costing $3,000 more than planned. Does the flip still make money?',
      input: {
        type: 'choice',
        options: [
          { id: 'yes', label: 'Yes, it still makes money' },
          { id: 'no', label: 'No, it loses money' },
        ],
      },
      correctChoice: ['no'],
    },
    {
      id: 's8b',
      kind: 'guided',
      label: 'Step 8b · how much',
      prompt: 'How many dollars does it make or lose? Type the number without a minus sign.',
      input: { type: 'number', unit: 'usd' },
      correct: 2100,
      codes: [{ code: 'GROSS', value: 7000 }],
    },
    {
      id: 's9',
      kind: 'choice',
      label: 'Step 9 · the 70% rule',
      prompt:
        'Some investors use a “70% rule”: pay at most 70% of what the finished house will sell for, minus the repairs. Does a $10,000 buy price pass this rule?',
      input: {
        type: 'choice',
        options: [
          { id: 'yes', label: 'Yes, it passes' },
          { id: 'no', label: 'No, it doesn’t pass' },
        ],
      },
      correctChoice: ['no'],
    },
    {
      id: 'post',
      kind: 'rating_post',
      label: 'Rating after the math',
      prompt: 'Now that you have worked through it, how believable is the claim?',
      input: { type: 'dial' },
    },
    {
      id: 's10a',
      kind: 'choice',
      label: 'Step 10 · what to check first',
      prompt: 'What would you check first before trusting this claim?',
      input: {
        type: 'choice',
        options: [
          { id: 'costs', label: 'All the costs, written down' },
          { id: 'sales', label: 'What similar houses really sold for' },
          { id: 'inspect', label: 'What an inspector finds' },
          { id: 'who', label: 'Who is making the claim, and what they gain' },
          { id: 'nothing', label: 'Nothing, it sounds fine' },
        ],
      },
    },
  ],
  admin: [
    { type: 'cardHeat', step: 's4a', title: 'Which costs students counted' },
    { type: 'dots', step: 's4b', title: 'Step 4b: net profit', axis: { min: 0, max: 12000, scale: 'linear', unit: 'usd' }, primary: true },
    { type: 'dumbbell', gut: 'gut', post: 'post', title: 'Believability: gut vs after the math' },
    { type: 'calibration', gut: 'gut', post: 'post', title: 'Calibration' },
    { type: 'choiceBar', step: 's8a', title: 'Step 8a: does it still make money after +$3,000 repairs?' },
    { type: 'choiceBar', step: 's10a', title: 'What students would check first' },
  ],
  decision:
    'If most students stack only repairs, cost-stack awareness is the first thing to teach. A big high-confidence-still-believes group makes “rate the claim before you compute it” the hook for the workshop.',
  notes: [
    'Scenario numbers (repairs, buying, holding, 8% selling costs, 165 days) are inputs from the spec, not market facts.',
    'Order: this problem’s gut rating comes before S4 and F5 (my reading of “before any other cost-related item”).',
    'Step 8 is split into a yes/no and an amount because the keypad has no minus sign.',
  ],
});
