import { defineProblem } from '../types';

/** DRAFT wording, from the Interaction & Admin Visual Spec, F5. */
export default defineProblem({
  id: 'F5',
  slug: 'sneaker-resale',
  title: 'Sneaker Resale',
  version: 1,
  active: true,
  draft: true,
  module: 'feasibility',
  deca_category: 'employment_income',
  families: ['feasibility', 'percent'],
  scenario: {
    layout: 'claim',
    who: '@sneakerking_dre',
    source: 'post',
    claim: 'Bought sneakers for $150. Sold them for $220. Easy $70! Do it every week.',
    facts: [
      { label: 'Bought for', value: '$150' },
      { label: 'Sold for', value: '$220' },
      { label: 'App fee', value: '12% of the sale price' },
      { label: 'Shipping', value: '$12' },
      { label: 'Time spent', value: '3 hours' },
    ],
  },
  steps: [
    {
      id: 'gut',
      kind: 'rating_gut',
      label: 'Gut rating',
      prompt: 'How believable is “easy money”? Go with your gut.',
      input: { type: 'dial' },
    },
    {
      id: 's1',
      kind: 'cold',
      label: 'Step 1 · profit guess',
      prompt: 'About how much money does this person really keep? Tap the line.',
      input: { type: 'numberLine', min: 0, max: 100, scale: 'linear', unit: 'usd' },
      correct: 31.6,
      codes: [
        { code: 'GROSS', value: 70 },
        { code: 'MISS', value: 43.6 },
        { code: 'MISS', value: 58 },
      ],
    },
    {
      id: 's2',
      kind: 'control',
      label: 'Step 2 · the app fee',
      prompt: 'The app takes 12% of the $220 sale price. How many dollars is the fee?',
      input: { type: 'number', unit: 'usd' },
      correct: 26.4,
      codes: [
        { code: 'PAD', value: 12 },
        { code: 'DEC', value: 2.64 },
      ],
    },
    {
      id: 's3a',
      kind: 'guided',
      label: 'Step 3a · profit stacker',
      prompt: 'Which of these should count when you work out the profit? Tap the ones that count.',
      input: {
        type: 'stack',
        poolLabel: 'Cards',
        areaLabel: 'What counts in the profit',
        cards: [
          { id: 'sale', label: 'Sale price', amount: '$220' },
          { id: 'purchase', label: 'What you paid for them', amount: '$150' },
          { id: 'fee', label: 'App fee', amount: '12% of the sale price' },
          { id: 'ship', label: 'Shipping', amount: '$12' },
          { id: 'cool', label: 'How cool the sneakers are', distractor: true },
        ],
      },
    },
    {
      id: 's3b',
      kind: 'guided',
      label: 'Step 3b · profit',
      prompt: 'After everything you counted, how much profit does this person make?',
      input: { type: 'number', unit: 'usd' },
      correct: 31.6,
      codes: [
        { code: 'GROSS', value: 70 },
        { code: 'MISS', value: 43.6 },
        { code: 'MISS', value: 58 },
      ],
    },
    {
      id: 's4',
      kind: 'guided',
      label: 'Step 4 · profit per hour',
      prompt: 'It took 3 hours in total. How much is the profit for each hour?',
      input: { type: 'number', unit: 'usd' },
      correct: 10.53,
      codes: [
        { code: 'GROSS', value: 23.33 },
        { code: 'MISS', value: 14.53 },
      ],
    },
    {
      id: 's5a',
      kind: 'choice',
      label: 'Step 5 · compared to a part-time job',
      prompt: 'Is that hourly profit more than, about the same as, or less than a part-time job?',
      input: {
        type: 'choice',
        options: [
          { id: 'more', label: 'More than a part-time job' },
          { id: 'same', label: 'About the same' },
          { id: 'less', label: 'Less than a part-time job' },
        ],
      },
    },
    {
      id: 's5b',
      kind: 'guided',
      label: 'Step 5 · part-time wage near you',
      prompt: 'About how much per hour does a part-time job pay near you?',
      input: { type: 'number', unit: 'usd' },
    },
    {
      id: 'post',
      kind: 'rating_post',
      label: 'Rating after the math',
      prompt: 'Now that you have worked through it, how believable is “easy money”?',
      input: { type: 'dial' },
    },
  ],
  admin: [
    {
      type: 'waterfall',
      stack: 's3a',
      profit: 's3b',
      title: 'Profit stacker: class average vs correct breakdown',
      cards: [
        { id: 'sale', label: 'Sale price', amount: 220, sign: 1 },
        { id: 'purchase', label: 'Purchase price', amount: 150, sign: -1 },
        { id: 'fee', label: 'App fee', amount: 26.4, sign: -1 },
        { id: 'ship', label: 'Shipping', amount: 12, sign: -1 },
      ],
      correct: 31.6,
    },
    {
      type: 'shareBar',
      step: 's3b',
      title: 'Step 3b: profit answers',
      buckets: [
        { label: '$31.60 (correct)', codes: ['CORR'] },
        { label: '$70 (gross)', codes: ['GROSS'] },
        { label: '$43.60 / $58 (a cost missing)', codes: ['MISS'] },
      ],
    },
    { type: 'dumbbell', gut: 'gut', post: 'post', title: 'Believability: gut vs after the math' },
    { type: 'calibration', gut: 'gut', post: 'post', title: 'Calibration' },
    { type: 'dots', step: 's1', title: 'Step 1: profit guess', primary: true },
  ],
  decision: 'Many $70 answers mean “profit” is being read as sale price minus purchase price.',
  notes: ['Fee, shipping and time are inputs from the spec, not market facts.'],
});
