import { defineProblem } from '../types';

/** DRAFT wording, from the Interaction & Admin Visual Spec, F8. Computed order = ascending yearly growth the claim needs. */
export default defineProblem({
  id: 'F8',
  slug: 'rank-the-claims',
  title: 'Rank the Claims',
  version: 1,
  active: true,
  draft: true,
  module: 'feasibility',
  deca_category: 'decision_making',
  families: ['feasibility'],
  scenario: { layout: 'situation', text: 'Five different people made money claims. You will rank them, check the math, and rank them again.' },
  steps: [
    {
      id: 's1',
      kind: 'rating_gut',
      label: 'First ranking',
      prompt: 'Put the claims in order, from the MOST believable at the top to the LEAST believable at the bottom.',
      input: {
        type: 'rank',
        topLabel: 'Most believable',
        bottomLabel: 'Least believable',
        cards: [
          { id: 'a', label: 'My savings account pays 4.2% a year.' },
          { id: 'b', label: 'I bought a house for $10,000, fixed it up, and sold it 165 days later. After all costs I made $900 on the $19,100 I put in.' },
          { id: 'c', label: '$200 in an account grows to $2,000 in 10 years.' },
          { id: 'd', label: 'Invest with us: we pay 12% every month, guaranteed.' },
          { id: 'e', label: 'I turned $500 into $50,000 in one year.' },
        ],
      },
    },
    {
      id: 's2a',
      kind: 'control',
      label: 'Claim A · yearly growth',
      prompt: 'Claim A: “My savings account pays 4.2% a year.” About what yearly growth is that, as a percent?',
      input: { type: 'number', unit: 'percent' },
      correct: 4.2,
    },
    {
      id: 's2b',
      kind: 'guided',
      label: 'Claim B · yearly growth',
      prompt: 'Claim B: $900 profit on $19,100 in 165 days. If that kept going, what would it be in a year (365 days)? Answer as a percent. You can use a calculator.',
      input: { type: 'number', unit: 'percent' },
      calculator: true,
      correct: 10.42,
      correctTolPct: 3.5,
    },
    {
      id: 's2c',
      kind: 'guided',
      label: 'Claim C · yearly growth',
      prompt: 'Claim C: $200 becomes $2,000 in 10 years. What yearly growth does that need, as a percent? You can use a calculator.',
      input: { type: 'number', unit: 'percent' },
      calculator: true,
      correct: 25.89,
      correctTolPct: 2,
      codes: [{ code: 'LIN', value: 80 }],
    },
    {
      id: 's2d',
      kind: 'guided',
      label: 'Claim D · yearly growth',
      prompt: 'Claim D: 12% every month for 12 months. What is that for the whole year, as a percent? You can use a calculator.',
      input: { type: 'number', unit: 'percent' },
      calculator: true,
      correct: 289.6,
      codes: [{ code: 'LIN', value: 144 }],
    },
    {
      id: 's2e',
      kind: 'guided',
      label: 'Claim E · yearly growth',
      prompt: 'Claim E: $500 becomes $50,000 in one year. How many percent is the growth? You can use a calculator.',
      input: { type: 'number', unit: 'percent' },
      calculator: true,
      correct: 9900,
      codes: [{ code: 'DEC', value: 10000 }],
    },
    {
      id: 's3',
      kind: 'rating_post',
      label: 'Second ranking',
      prompt: 'Now that you have checked the math, put the claims in order again: MOST believable at the top, LEAST believable at the bottom.',
      input: {
        type: 'rank',
        topLabel: 'Most believable',
        bottomLabel: 'Least believable',
        cards: [
          { id: 'a', label: 'My savings account pays 4.2% a year.' },
          { id: 'b', label: 'I bought a house for $10,000, fixed it up, and sold it 165 days later. After all costs I made $900 on the $19,100 I put in.' },
          { id: 'c', label: '$200 in an account grows to $2,000 in 10 years.' },
          { id: 'd', label: 'Invest with us: we pay 12% every month, guaranteed.' },
          { id: 'e', label: 'I turned $500 into $50,000 in one year.' },
        ],
      },
    },
  ],
  admin: [
    {
      type: 'slope',
      title: 'Average rank: first guess → second guess → computed order',
      first: 's1',
      second: 's3',
      order: ['a', 'b', 'c', 'd', 'e'],
      labels: { a: 'A · 4.2% savings', b: 'B · house flip', c: 'C · $200 → $2,000', d: 'D · 12% a month', e: 'E · $500 → $50,000' },
    },
    { type: 'rankCorr', title: 'How close each student’s ranking is to the computed order', first: 's1', second: 's3', order: ['a', 'b', 'c', 'd', 'e'] },
    { type: 'firstLast', title: 'Who ranked each claim first or last (first ranking)', step: 's1', labels: { a: 'A · 4.2% savings', b: 'B · house flip', c: 'C · $200 → $2,000', d: 'D · 12% a month', e: 'E · $500 → $50,000' } },
    { type: 'firstLast', title: 'Who ranked each claim first or last (second ranking)', step: 's3', labels: { a: 'A · 4.2% savings', b: 'B · house flip', c: 'C · $200 → $2,000', d: 'D · 12% a month', e: 'E · $500 → $50,000' } },
  ],
  decision: 'A low first-ranking agreement with a high second one means the math works but intuition doesn’t. Open with the most mis-ranked claim.',
  notes: ['Computed order = least to most yearly growth needed (A, B, C, D, E). It ranks how demanding each claim is, not whether it is a scam.'],
});
