import { defineProblem } from '../types';

/** DRAFT wording, from the Interaction & Admin Visual Spec, H1. Shown only after S6 (see order rules). */
export default defineProblem({
  id: 'H1',
  slug: '200-to-2000',
  title: '“$200 Becomes $2,000”',
  version: 1,
  active: true,
  draft: true,
  module: 'hybrid',
  deca_category: 'investing',
  families: ['feasibility', 'compounding'],
  scenario: {
    layout: 'claim',
    who: '@early_bird_invests',
    source: 'chat',
    claim: 'Put $200 in an account that pays 8% a year. In 10 years it becomes $2,000. Start early!',
  },
  steps: [
    {
      id: 'gut',
      kind: 'rating_gut',
      label: 'Gut rating',
      prompt: 'How believable is this claim? Go with your gut.',
      input: { type: 'dial' },
    },
    {
      id: 's1',
      kind: 'cold',
      label: 'Step 1 · balance guess',
      prompt: 'About how much would $200 at 8% a year be worth after 10 years? Tap the line.',
      input: { type: 'numberLine', min: 0, max: 3000, scale: 'linear', unit: 'usd' },
      correct: 431.78,
      codes: [
        { code: 'LIN', value: 360 },
        { code: 'CLAIM', value: 2000 },
      ],
    },
    {
      id: 's2',
      kind: 'control',
      label: 'Step 2 · balance after 1 year',
      prompt: 'How much money is in the account after 1 year?',
      input: { type: 'number', unit: 'usd' },
      correct: 216,
      codes: [
        { code: 'INTONLY', value: 16 },
        { code: 'PAD', value: 208 },
      ],
    },
    {
      id: 's3',
      kind: 'guided',
      label: 'Step 3 · actual balance after 10 years',
      prompt: 'Now work it out. How much is in the account after 10 years at 8% a year? You can use a calculator.',
      input: { type: 'number', unit: 'usd' },
      calculator: true,
      correct: 431.78,
      codes: [
        { code: 'LIN', value: 360 },
        { code: 'CLAIM', value: 2000 },
      ],
    },
    {
      id: 's4',
      kind: 'guided',
      label: 'Step 4 · rate the claim would need',
      prompt: 'About what yearly interest rate would it take to turn $200 into $2,000 in 10 years? Tap the line.',
      input: { type: 'numberLine', min: 0, max: 100, scale: 'linear', unit: 'percent' },
      correct: 25.89,
      codes: [{ code: 'LIN', value: 80 }],
    },
    {
      id: 'post',
      kind: 'rating_post',
      label: 'Rating after the math',
      prompt: 'Now that you have worked through it, how believable is the claim?',
      input: { type: 'dial' },
    },
    {
      id: 's5',
      kind: 'choice',
      label: 'What I’d ask',
      prompt: 'What would you ask the person who said this?',
      input: {
        type: 'choice',
        options: [
          { id: 'rate', label: 'What interest rate does the account really pay?' },
          { id: 'where', label: 'Which account is this, and is it real?' },
          { id: 'proof', label: 'Can you show me your statements?' },
          { id: 'gain', label: 'What do you get if I sign up?' },
          { id: 'nothing', label: 'Nothing, it sounds fine' },
        ],
      },
    },
  ],
  admin: [
    {
      type: 'quadrants',
      title: 'Compounding skill × belief',
      x: { step: 's1', ref: 431.78, withinPct: 25, good: 'Compounds well', bad: 'Doesn’t compound well' },
      belief: { step: 'post', min: 4, yes: 'believes the claim', no: 'doubts the claim' },
    },
    {
      type: 'scatter',
      title: 'Balance guess vs rate guess',
      x: { step: 's1', axis: { min: 100, max: 3000, scale: 'log', unit: 'usd' } },
      y: { step: 's4', axis: { min: 0, max: 100, scale: 'linear', unit: 'percent' } },
      refX: 431.78,
      refY: 25.89,
      belief: { step: 'post', min: 4 },
      note: 'Diamonds: still rated the claim 4–5 after the math. Lines mark the true values.',
    },
    { type: 'dots', step: 's4', title: 'Step 4: rate needed', primary: true },
    { type: 'dumbbell', gut: 'gut', post: 'post', title: 'Believability: gut vs after the math' },
    { type: 'calibration', gut: 'gut', post: 'post', title: 'Calibration' },
  ],
  decision: 'The “doesn’t compound well, believes the claim” group is the highest-risk one.',
  notes: ['Shown only after S6 so the claim cannot anchor S6 (order rule on S6).'],
});
