import { defineProblem } from '../types';

/** DRAFT wording, from the Interaction & Admin Visual Spec, S6. $200 at 8% for 10 years. */
export default defineProblem({
  id: 'S6',
  slug: 'birthday-deposit',
  title: 'The $200 Birthday Deposit',
  version: 1,
  active: true,
  draft: true,
  module: 'skill',
  deca_category: 'investing',
  families: ['compounding'],
  scenario: {
    layout: 'situation',
    text: 'You get $200 for your birthday and put it in an account that pays 8% interest a year. You never add or take out money.',
    facts: [
      { label: 'Start', value: '$200' },
      { label: 'Interest', value: '8% a year' },
      { label: 'Time', value: '10 years' },
    ],
  },
  order: { before: ['H1'], notAdjacent: ['S7', 'S8'] },
  steps: [
    {
      id: 's1',
      kind: 'cold',
      label: 'Step 1 · draw the growth',
      prompt: 'Draw how your money grows. Place a point for year 10. You can also place a point for year 5.',
      input: { type: 'curve', xMax: 10, yMax: 1000, start: 200, midX: 5, unit: 'usd' },
      correct: 431.78,
      codes: [{ code: 'LIN', value: 360 }],
    },
    {
      id: 's2',
      kind: 'control',
      label: 'Step 2 · balance after 1 year',
      prompt: 'How much money is in the account after 1 year?',
      input: { type: 'number', unit: 'usd' },
      correct: 216,
      codes: [
        { code: 'INTONLY', value: 16 },
        { code: 'PAD', value: 208 },
      ],
    },
    {
      id: 's3a',
      kind: 'guided',
      label: 'Step 3a · balance after 2 years',
      prompt: 'How much is in the account after 2 years?',
      input: { type: 'number', unit: 'usd' },
      correct: 233.28,
      correctTolPct: 0.2, // $232 (simple) is 0.5% below $233.28 (compound)
      codes: [{ code: 'LIN', value: 232, tolPct: 0.2 }],
    },
    {
      id: 's3b',
      kind: 'guided',
      label: 'Step 3b · interest earned in year 2',
      prompt: 'How much interest did the account earn during year 2?',
      input: { type: 'number', unit: 'usd' },
      correct: 17.28,
      codes: [{ code: 'LIN', value: 16 }],
    },
    {
      id: 's4',
      kind: 'guided',
      label: 'Step 4 · years to double',
      prompt: 'About how many years until the $200 becomes $400? Tap the line.',
      input: { type: 'numberLine', min: 0, max: 40, scale: 'linear', unit: 'years' },
      correct: 9.01,
      correctTolPct: 2,
      codes: [{ code: 'LIN', value: 12.5 }],
    },
    {
      id: 's5',
      kind: 'guided',
      label: 'Step 5 · extra from compounding',
      prompt: 'If the account paid the same $16 every year (no interest on interest), it would have $360 after 10 years. How many MORE dollars does it really have?',
      input: { type: 'number', unit: 'usd' },
      correct: 71.78,
      codes: [{ code: 'SAMEASCOMP', value: 0 }],
    },
  ],
  admin: [
    {
      type: 'spaghetti',
      step: 's1',
      title: 'Every student’s growth curve',
      start: 200,
      xMax: 10,
      yMax: 1000,
      midX: 5,
      linear: [280, 360],
      truth: [293.87, 431.78],
      unit: 'usd',
    },
    { type: 'curveShapes', step: 's1', title: 'Curve shapes', start: 200, midX: 5 },
    {
      type: 'scatter',
      title: 'Can compute year 1, but draws a straight line?',
      x: { step: 's2', mode: 'correct' },
      y: { step: 's1', axis: { min: 0, max: 1000, scale: 'linear', unit: 'usd' } },
      note: 'Left column: Step 2 wrong. Right column: Step 2 right. Height: the year-10 point they drew.',
    },
    { type: 'dots', step: 's1', title: 'Year-10 point', axis: { min: 0, max: 1000, scale: 'linear', unit: 'usd' }, primary: true },
  ],
  decision: 'Lots of straight lines with a correct Step 2 means the gap is intuition about compounding, not arithmetic.',
  notes: ['Step 3a uses ±0.2% bands so $232 (simple) and $233.28 (compound) are told apart.', 'Y-axis is fixed at $0–$1,000 for every student and every workshop. Changing it shifts answers, so don’t pool across a change.'],
});
