import { defineProblem } from '../types';

/** DRAFT wording, from the Interaction & Admin Visual Spec, S13. Prices rise 3.4% a year; ten $10 items. */
export default defineProblem({
  id: 'S13',
  slug: 'will-100-buy-100',
  title: 'Will $100 Still Buy $100?',
  version: 1,
  active: true,
  draft: true,
  module: 'skill',
  deca_category: 'spending_saving',
  families: ['percent', 'compounding'],
  scenario: {
    layout: 'situation',
    text: 'A shelf has 10 identical items. Each costs $10 today, so $100 buys all 10. Prices go up 3.4% a year.',
    facts: [
      { label: 'Each item today', value: '$10' },
      { label: 'Prices go up', value: '3.4% a year' },
      { label: 'Your money', value: '$100' },
    ],
  },
  steps: [
    {
      id: 's1a',
      kind: 'cold',
      label: 'Step 1a · items $100 buys next year',
      prompt: 'Next year, how many of the 10 items will your $100 still buy? Tap the shelf.',
      input: { type: 'dotGrid', total: 10, columns: 10, itemWord: 'item' },
      correct: 9.67,
      correctTolPct: 0.5, // whole-number answers never match 9.67; the dashboard buckets them instead
      noUnk: true,
      codes: [{ code: 'ILLUSION', value: 10 }],
    },
    {
      id: 's1b',
      kind: 'cold',
      label: 'Step 1b · cost of the basket next year',
      prompt: 'Next year, what will the same 10 items cost in total?',
      input: { type: 'number', unit: 'usd' },
      correct: 103.4,
      codes: [
        { code: 'ILLUSION', value: 100 },
        { code: 'DEC', value: 134 },
      ],
    },
    {
      id: 's2',
      kind: 'control',
      label: 'Step 2 · next year’s $100 in today’s dollars',
      prompt: 'Next year, $100 will buy only as much as how many of TODAY’S dollars buy? (Prices are 3.4% higher.)',
      input: { type: 'number', unit: 'usd' },
      correct: 96.71,
      codes: [
        { code: 'ILLUSION', value: 100 },
        { code: 'DEC', value: 74.63 },
      ],
    },
    {
      id: 's3a',
      kind: 'guided',
      label: 'Step 3a · piggy bank (0%)',
      prompt: 'You keep $100 in a piggy bank for a year. It earns nothing. In today’s dollars, what is it worth next year?',
      input: { type: 'number', unit: 'usd' },
      correct: 96.71,
      codes: [{ code: 'ILLUSION', value: 100 }],
    },
    {
      id: 's3b',
      kind: 'guided',
      label: 'Step 3b · savings account (0.37%)',
      prompt: 'You put $100 in a savings account that pays 0.37% for a year. In today’s dollars, what is it worth next year?',
      input: { type: 'number', unit: 'usd' },
      calculator: true,
      correct: 97.07,
      codes: [{ code: 'ILLUSION', value: 100.37 }],
    },
    {
      id: 's3c',
      kind: 'guided',
      label: 'Step 3c · high-yield account (4%)',
      prompt: 'You put $100 in a high-yield account that pays 4% for a year. In today’s dollars, what is it worth next year?',
      input: { type: 'number', unit: 'usd' },
      calculator: true,
      correct: 100.58,
      codes: [{ code: 'ILLUSION', value: 104 }],
    },
    {
      id: 's4',
      kind: 'guided',
      label: 'Step 4 · cost in 10 years',
      prompt: 'If prices keep going up 3.4% a year, what will the $100 basket cost in 10 years? You can use a calculator.',
      input: { type: 'number', unit: 'usd' },
      calculator: true,
      correct: 139.7,
      codes: [
        { code: 'LIN', value: 134 },
        { code: 'ILLUSION', value: 100 },
      ],
    },
  ],
  admin: [
    { type: 'dots', step: 's1b', title: 'Step 1b: cost of the basket next year', axis: { min: 90, max: 145, scale: 'linear', unit: 'usd' }, primary: true },
    {
      type: 'valueBuckets',
      title: 'Step 1a: how many items $100 still buys',
      step: 's1a',
      note: 'The true answer is 9.7: you can buy 9 and have some money left.',
      buckets: [
        { label: '11 or more', min: 10.5, max: Infinity, tone: 'neutral' },
        { label: '10 (same as today)', min: 9.5, max: 10.5, tone: 'wrong' },
        { label: '9', min: 8.5, max: 9.5, tone: 'corr' },
        { label: '8 or fewer', min: -Infinity, max: 8.5, tone: 'neutral' },
      ],
    },
    {
      type: 'valueBuckets',
      title: 'Step 3a: piggy bank worth next year (in today’s dollars)',
      step: 's3a',
      buckets: [
        { label: 'Less than $100 (right direction)', min: -Infinity, max: 99.995, tone: 'corr' },
        { label: 'Exactly $100', min: 99.995, max: 100.005, tone: 'wrong' },
        { label: 'More than $100', min: 100.005, max: Infinity, tone: 'neutral' },
      ],
    },
    { type: 'codeBar', steps: ['s1b', 's2', 's3a', 's3b', 's3c', 's4'], title: 'Where the error shows up, by step' },
  ],
  decision: 'Many $100 answers mean students treat nominal and real value as the same thing.',
});
